service: test-variables-resolvers

provider:
  name: aws
  stage: 'dev'
  region: 'us-east-1'


################################################################################
# PLUGINS
################################################################################

plugins:
  - serverless-aws-utils


################################################################################
# PLUGINS CONFIGURATION
################################################################################

custom:
  vault:
    key: key-preffix-${self:custom.provider.stage}
    path: /v1/secret/${self:custom.vault.key}
    host: "vault.corp.aws"
  certName: 'dev.some_app.us-east-1.domain.com'
  certificateArn: ${certificate:${self:custom.certName}}
  hostedZoneId: ${hostedZoneId:${self:custom.certName}}

resources:
  Resources:
    StaticWebSiteBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        AccessControl: Private
        BucketName: '${self:custom.certificateArn}--aaa'
        BucketName2: '${self:custom.hostedZoneId}--aaa'
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
